name: Flake8 check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "150"
          plugins: "flake8-bugbear pep8-naming flake8-pyproject"